dev:
	@(echo "\n** Run \`make build\` for production **")
	npm run dev

build:
	npm run build

install: package.json
	@echo "Installing frontend JavaScript requirements:"
	@npm install --no-fund

.PHONY: build