# Generated by Django 4.0.3 on 2022-04-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0002_remove_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUNDING_AGENCIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=100)),
                ('fa_type', models.CharField(max_length=100)),
                ('fa_mission', models.CharField(max_length=500)),
                ('fa_website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MONITOR_LOCATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('loc_lat', models.IntegerField()),
                ('loc_long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_class', models.CharField(max_length=100)),
                ('org_description', models.CharField(max_length=500)),
                ('org_website', models.CharField(max_length=100)),
                ('org_email', models.EmailField(max_length=100)),
                ('org_address', models.CharField(max_length=100)),
                ('org_city', models.CharField(max_length=50)),
                ('org_state', models.CharField(max_length=10)),
                ('org_zip', models.IntegerField()),
                ('org_country', models.CharField(max_length=10)),
                ('org_title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PROJECTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.CharField(max_length=100)),
                ('tools_used', models.CharField(max_length=200)),
                ('project_startdate', models.DateField()),
                ('project_enddate', models.DateField()),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.funding_agencies')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.monitor_locations')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.organization')),
            ],
        ),
    ]
