# Generated by Django 4.0.3 on 2022-04-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0003_funding_agencies_monitor_locations_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FUNDING_AGENCIES',
            new_name='FUNDING_AGENCY',
        ),
        migrations.RenameModel(
            old_name='MONITOR_LOCATIONS',
            new_name='MONITOR_LOCATION',
        ),
        migrations.RenameModel(
            old_name='PROJECTS',
            new_name='PROJECT',
        ),
    ]
