# Generated by Django 4.0.3 on 2022-04-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0005_project_project_name_alter_monitor_location_loc_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='fa',
            new_name='project_fa',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='org',
            new_name='project_org',
        ),
        migrations.RemoveField(
            model_name='project',
            name='loc',
        ),
        migrations.AddField(
            model_name='project',
            name='loc_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='loc_long',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_loc',
            field=models.CharField(default='Tijuana', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='active_status',
            field=models.BooleanField(unique=b'I01\n'),
        ),
        migrations.DeleteModel(
            name='MONITOR_LOCATION',
        ),
    ]
