# Generated by Django 4.0.3 on 2022-04-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0006_rename_fa_project_project_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_enddate',
            field=models.DateField(default=b'N'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_fa',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='FUNDING_AGENCY',
        ),
    ]
