# Generated by Django 4.0.4 on 2022-04-26 22:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0007_alter_project_project_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_class',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_zip',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_org',
            new_name='fk_organization',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_fa',
            new_name='funding_agencies',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='active_status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tools_used',
            new_name='parameters_monitored',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_startdate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='loc_lat',
        ),
        migrations.RemoveField(
            model_name='project',
            name='loc_long',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_loc',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='fk_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contribute.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.TextField(default='butter', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='fk_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contribute.location'),
            preserve_default=False,
        ),
    ]
