# Generated by Django 4.0.4 on 2022-04-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0008_location_rename_org_address_organization_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
