# Generated by Django 4.0.4 on 2022-04-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0011_remove_project_parameters_monitored_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PARAMETERS',
        ),
    ]
