# Generated by Django 4.0.4 on 2022-05-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0014_remove_project_latitude_remove_project_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='zip_code',
            new_name='zip',
        ),
        migrations.RemoveField(
            model_name='project',
            name='params_default',
        ),
        migrations.RemoveField(
            model_name='project',
            name='params_other',
        ),
        migrations.AddField(
            model_name='project',
            name='parameters_monitored',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='fk_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.organization'),
        ),
    ]
