# Generated by Django 4.0.4 on 2022-05-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0015_rename_zip_code_organization_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(unique=True),
        ),
    ]
