# Generated by Django 4.0.3 on 2022-05-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0017_rename_zip_organization_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('MX', 'Mexico'), ('CAN', 'Canada')], max_length=20),
        ),
    ]
