# Generated by Django 4.0.4 on 2022-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0018_alter_organization_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('A', 'Academic'), ('M', 'Municipal'), ('S', 'State'), ('F', 'Federal'), ('I', 'International'), ('N', 'Non-Profit'), ('i', 'Individual'), ('O', 'Other')], max_length=10),
        ),
    ]
