# Generated by Django 4.0.4 on 2022-05-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0019_alter_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('A', 'Academic'), ('F', 'Federal'), ('I', 'International'), ('N', 'Non-Profit'), ('M', 'Municipal'), ('S', 'State'), ('O', 'Other')], max_length=10),
        ),
    ]
