# Generated by Django 4.0.4 on 2022-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0023_alter_project_params_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agencies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='params_other',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
